import type { Metadata } from "next";
import localFont from "next/font/local";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";


const poppins = Poppins({
  weight: ['400', '500', '600', '700'],  // specify needed weights
  subsets: ['latin'],
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
            <div className="w-screen h-fit fixed left-0 top-3 px-0 z-40">

<Navbar  />
</div>
     
        {children}
      </body>
    </html>
  );
}
